// This file is auto-generated by @hey-api/openapi-ts

export type PresetValueDto = {
    docTypeId: string;
    propertyAlias: string;
    value?: unknown;
};

export type GetPresetValuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/preset-values';
};

export type GetPresetValuesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPresetValuesResponses = {
    /**
     * OK
     */
    200: Array<PresetValueDto>;
};

export type GetPresetValuesResponse = GetPresetValuesResponses[keyof GetPresetValuesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44323' | (string & {});
};